# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddComponentsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddComponentsDialog(object):
    def setupUi(self, AddComponentsDialog):
        AddComponentsDialog.setObjectName("AddComponentsDialog")
        AddComponentsDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        AddComponentsDialog.setEnabled(True)
        AddComponentsDialog.resize(313, 287)
        AddComponentsDialog.setMinimumSize(QtCore.QSize(272, 270))
        self.groupBox = QtWidgets.QGroupBox(AddComponentsDialog)
        self.groupBox.setGeometry(QtCore.QRect(11, 11, 291, 231))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 2)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ValueLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ValueLineEdit.sizePolicy().hasHeightForWidth())
        self.ValueLineEdit.setSizePolicy(sizePolicy)
        self.ValueLineEdit.setObjectName("ValueLineEdit")
        self.gridLayout.addWidget(self.ValueLineEdit, 1, 1, 1, 1)
        self.ValueUnitLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ValueUnitLineEdit.sizePolicy().hasHeightForWidth())
        self.ValueUnitLineEdit.setSizePolicy(sizePolicy)
        self.ValueUnitLineEdit.setObjectName("ValueUnitLineEdit")
        self.gridLayout.addWidget(self.ValueUnitLineEdit, 1, 2, 1, 1)
        self.FrqUnitLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrqUnitLineEdit.sizePolicy().hasHeightForWidth())
        self.FrqUnitLineEdit.setSizePolicy(sizePolicy)
        self.FrqUnitLineEdit.setObjectName("FrqUnitLineEdit")
        self.gridLayout.addWidget(self.FrqUnitLineEdit, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.FrqLineEdit = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrqLineEdit.sizePolicy().hasHeightForWidth())
        self.FrqLineEdit.setSizePolicy(sizePolicy)
        self.FrqLineEdit.setObjectName("FrqLineEdit")
        self.gridLayout.addWidget(self.FrqLineEdit, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.NameLineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.NameLineEdit.setObjectName("NameLineEdit")
        self.gridLayout.addWidget(self.NameLineEdit, 3, 1, 1, 2)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddComponentsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(90, 250, 193, 28))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(AddComponentsDialog)
        self.buttonBox.rejected.connect(AddComponentsDialog.reject)
        self.buttonBox.accepted.connect(AddComponentsDialog.accept)
        self.comboBox.currentIndexChanged['QString'].connect(AddComponentsDialog.showFreq)
        QtCore.QMetaObject.connectSlotsByName(AddComponentsDialog)
        AddComponentsDialog.setTabOrder(self.comboBox, self.ValueLineEdit)
        AddComponentsDialog.setTabOrder(self.ValueLineEdit, self.FrqLineEdit)
        AddComponentsDialog.setTabOrder(self.FrqLineEdit, self.NameLineEdit)
        AddComponentsDialog.setTabOrder(self.NameLineEdit, self.ValueUnitLineEdit)
        AddComponentsDialog.setTabOrder(self.ValueUnitLineEdit, self.FrqUnitLineEdit)

    def retranslateUi(self, AddComponentsDialog):
        _translate = QtCore.QCoreApplication.translate
        AddComponentsDialog.setWindowTitle(_translate("AddComponentsDialog", "Add..."))
        self.groupBox.setTitle(_translate("AddComponentsDialog", "Add Components"))
        self.comboBox.setItemText(0, _translate("AddComponentsDialog", "Resistor (R)"))
        self.comboBox.setItemText(1, _translate("AddComponentsDialog", "Capacitor (C)"))
        self.comboBox.setItemText(2, _translate("AddComponentsDialog", "Inductance (L)"))
        self.comboBox.setItemText(3, _translate("AddComponentsDialog", "DC_Power"))
        self.comboBox.setItemText(4, _translate("AddComponentsDialog", "DC_Current"))
        self.comboBox.setItemText(5, _translate("AddComponentsDialog", "AC_Power"))
        self.comboBox.setItemText(6, _translate("AddComponentsDialog", "AC_Current"))
        self.label.setText(_translate("AddComponentsDialog", "Type"))
        self.label_6.setText(_translate("AddComponentsDialog", "Freqency"))
        self.label_3.setText(_translate("AddComponentsDialog", "Value"))
        self.label_2.setText(_translate("AddComponentsDialog", "Name"))
        self.NameLineEdit.setPlaceholderText(_translate("AddComponentsDialog", "New name"))
